import {test} from 'node:test';import assert from 'node:assert/strict';
import {connectDisplayParent,connectDisplayChild} from '../display-session.js';
function harness(){let listener,timer,cleared=false;const messages=[],errors=[],peer={closed:false,postMessage:(...x)=>messages.push(x)};const host={location:{origin:'https://fixture.test'},opener:peer,addEventListener:(type,cb)=>{listener=cb;},removeEventListener:()=>{listener=null;}};return {host,peer,messages,errors,options:{host,nonce:'fixture-nonce',popup:peer,onError:x=>errors.push(x),setTimer:cb=>{timer=cb;return 1;},clearTimer:()=>{cleared=true;}},event:(type,extra={})=>({origin:host.location.origin,source:peer,data:{type,nonce:'fixture-nonce',token:'fixture-token'},...extra}),send:async e=>listener?.(e),expire:()=>timer(),listening:()=>!!listener};}
for(const side of ['parent','child']){
 test(side+' rejects foreign origin, window and nonce',async()=>{const h=harness();let calls=0;const start=side==='parent'?connectDisplayParent:connectDisplayChild;start({...h.options,issueToken:async()=>{calls++;return {token:'fixture'};},signIn:async()=>{calls++;}});const type=side==='parent'?'mci-display-ready':'mci-display-token';for(const extra of [{origin:'https://foreign.test'},{source:{}},{data:{type,nonce:'wrong',token:'fixture'}}])await h.send(h.event(type,extra));assert.equal(calls,0);});
 test(side+' accepts message only once',async()=>{const h=harness();let calls=0;const start=side==='parent'?connectDisplayParent:connectDisplayChild;start({...h.options,issueToken:async()=>{calls++;return {token:'fixture'};},signIn:async()=>{calls++;}});const e=h.event(side==='parent'?'mci-display-ready':'mci-display-token');await h.send(e);await h.send(e);assert.equal(calls,1);assert(!h.listening());});
 test(side+' explains connection timeout and removes listener',()=>{const h=harness();(side==='parent'?connectDisplayParent:connectDisplayChild)({...h.options,issueToken:async()=>({token:'fixture'}),signIn:async()=>{}});h.expire();assert.equal(h.errors.length,1);assert(!h.listening());});
}
test('parent cannot send a token after connection timeout',async()=>{const h=harness();let resolve;connectDisplayParent({...h.options,issueToken:()=>new Promise(r=>{resolve=r;})});const pending=h.send(h.event('mci-display-ready'));h.expire();resolve({token:'late'});await pending;assert.equal(h.messages.length,0);});
test('child without opener explains how to reopen',()=>{const h=harness();h.host.opener=null;connectDisplayChild({...h.options,signIn:async()=>{}});assert.equal(h.errors.length,1);assert(!h.listening());});
test('child reports authentication failure',async()=>{const h=harness();connectDisplayChild({...h.options,signIn:async()=>{throw Error('rejected');}});await h.send(h.event('mci-display-token'));assert.equal(h.errors.length,1);});
